# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e4fac4b097b57a8ec6e4d6964c0c17472cf9b7d23c122836540e64fe5cdd7102c60479817556ed16f99b0e10f07f6beeb4d07728996dfdef456fa03a8bf025f

test:
  secret_key_base: 1bf8c7fbe492b3eb6c7ee963e29034e382234064e085337c075e1058001c5894a039d2a2ff31593374a61417fbec45482c5b3b61ed2112b2fca9a3fa7d75c8af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
